[package]
name = "tempmon-rs"
version = "0.1.0"
authors = ["Ed Sweeney <ed@onextent.com>"]

[dependencies]
mqtt3 = "0.1.4"
netopt = "0.1.3"
mqttc = "0.1.4"
ws = "0.7.6"
config = "0.9"
serde_derive = "^1.0.8"
serde = "^1.0.8"
actix = "0.7"
futures = "0.1.23"
crossbeam-channel = "0.2"
mraa = "0.0.1"
